services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres52
      POSTGRES_DB: hackaton_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi-app:
    build: .
    container_name: fastapi-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DB_ADMIN=postgresql://postgres:postgres52@postgres:5432/hackaton_db
      - DATABASE_URL=postgresql://postgres:postgres52@postgres:5432/hackaton_db
      - SECRET_KEY=67-key-67
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - ./2/web_scraping.db:/app/2/web_scraping.db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  parser-app:
    build: .
    container_name: parser-app
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - DB_ADMIN=postgresql://postgres:postgres52@postgres:5432/hackaton_db
      - DATABASE_URL=postgresql://postgres:postgres52@postgres:5432/hackaton_db
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ./2/web_scraping.db:/app/2/web_scraping.db
    command: uvicorn parser_app:app --host 0.0.0.0 --port 8001 --reload

volumes:
  postgres_data:
