services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres52
      POSTGRES_DB: hackaton_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    environment:
      DB_ADMIN: postgresql://postgres:postgres52@postgres/hackaton_db
      JWT_SECRET_KEY: adnjawnjdNAWHDBAHWproduction
      JWT_ALGORITHM: HS256
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 100
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "python -m alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:
